export const ADMIN_ROUTE = "/admin";
export const LOGIN_ROUTE = "/login";
export const REGISTRATION_ROUTE = "/registration";
export const MAIN_ROUTE = "/";
export const TESTS_ROUTE = "/tests";
export const SEARCH_ROUTE = "/tests/search";
export const TEST_ROUTE = "/test";
export const PUBLIC_TEST_ROUTE = "/public/test";
// export const USERINFO_ROUTE = '/userinfo'
export const CREATE_ROUTE = "/create";
export const TESTILEU_ROUTE = "/testileu";
export const RESULTS_ROUTE = "/results";
export const GAMERESULTS_ROUTE = "/gameresults";
